### PR TITLE
feat: add unique ids to generated html

### LINKED ISSUE #15: Add ID from title
It would be good to have, say, the following:

~~~
```admonish tip "Hello"
...
```
~~~

to generate a `div` with an `id` (like for MarkDown titles) that comes from the title:

```html
<div class="admonition-title" id="hello">
```

This way it is possible to refer to this admonition in a URL link.

### PR DESCRIPTION
**Pull request by tommilligan**
Closes #15

I investigated whether there was an easy 'click to link to this admonition', but it's not clear to me what the UX of this should be, so that's open if anyone wants to work on it.

### CODE REVIEW

**Comment by schungx** [comment]
Probably best to also put a hyperlink `<a>` tag on the title pointing to the id, just like MarkDown titles.  This way it is much easier to "Copy Link".

As for the particular id itself, it doesn't really matter, as any non-conflicting ID would work fine.  The current implementation seems fine to me!

**Comment by schungx** [comment]
```html
<div class="admonition abstract">
<div id="admonition-what-is-this" class="admonition abstract">
<div class="admonition-title">
<a href="#admonition-what-is-this"><p>What <i>is</i> this?</p></a>
</div>
<div>
```

**Comment by tommilligan** [comment]
> Probably best to also put a hyperlink `<a>` tag on the title pointing to the id, just like MarkDown titles. This way it is much easier to "Copy Link".

Agreed - however this will require some level of styling/css changes which I don't have bandwidth for at the moment:

- wrapping the title in an `a` tag causes some formatting issues that need to be ironed out
- what happens if you have a hyperlink in the title already
  - maybe an icon that appears on hover would be better

For this PR I'll just merge the id attachment as that's simple and uncontroversial - if anyone wants to contribute a copy-on-link feature I'd be very open to it!

**Comment by schungx** [comment]
Without an anchor tag, some browsers (e.g. Chrome & FireFox) don't give a <kbd>Copy Link Address</kbd> option, which makes it difficult to actually get that auto-generated link id.

I've found that the following seems to work well enough, which is how `mdbook` does it for headings:

```html
<p><a class="header" href="#my-id-link">The admonition title</a></p>
```

The formatting will be seamless, and you can now <kbd>Copy Link Address</kbd> by right-clicking on the admonition title.

**Pull request merged**
