### PR TITLE
only modify `summary` with the `admonition-title` class

### PR DESCRIPTION
**Pull request by ImUrX**
it affected the styling of the summaries we use :P

### CODE REVIEW

**Comment by ImUrX** [comment]
ah, i didnt notice that, sorry, my fault on not reading the contributing section :sweat:

**Comment by tommilligan** [comment]
No worries at all! Thanks for the fix, my bad for not understanding how `:if` works before adopting it.

**Comment by ImUrX** [comment]
`:is()` is very similar to just using `,` in CSS, but it's more forgiving and readable :p

**Comment by tommilligan** [comment]
Released in v1.10.1

**Pull request merged**
