### PR TITLE
feat: add support for test renderer, running doctests

### LINKED ISSUE #108: Admonish doesn't work with `mdbook test`
If I use an admonish example (or other box) containing a code example, `mdbook test` will not test that example.
Here's an example of an example that doesn't get tested.

`````````
``````admonish example
Here's an example
```rust
let x = 10;
x = 20;
```
``````
`````````

If I take it out of an `admonish example` fenced code block, the code is tested (and fails as expected).

Is there a way to make this work?

### PR DESCRIPTION
**Pull request by tommilligan**
Closes #108

Adds support for the `test` renderer used by `mdbook test` to run doctests.

This required implementing a new method to simply strip all `admonish` syntax after relevant blocks are identified and parsed, leaving behind the content (basically in an "unwrapped" form)

This _should not_ be a breaking change, as all block content is subject to further rendering from the markdown engine anyway in the standard `html` render pipeline. However, this will definitely be a minor/feature release. It could technically be breaking if tests that were previously undetected now fail, but I'd argue that's a bugfix.

@stevecheckoway open for comments on if this fits your use case, and if you think there are any other details I've missed

### CODE REVIEW

**Comment by stevecheckoway** [comment]
I did a quick test. I cloned the repo, checked out the commit in this PR, and then updated my `book.toml` to point the command to the newly build mdbook-admonish. Running `mdbook test` seemed to correctly test my code (and I now get a bunch of expected errors due to missing crates in my examples).

I _think_ this might be a breaking change with respect to semvar, but I'm hardly an expert. You could introduce a configuration switch like this.
```toml
[preprocessor.admonish]
renderers = ["html", "test"]
```
I copied that example from the configuration I see for `mdbook-katex`.

But I'm happy with this as is.

**Comment by tommilligan** [comment]
That's an excellent idea. I'll add a renderer option in the next minor version, and add a note to enable it by default for next major version

**Comment by stevecheckoway** [comment]
Thanks for looking into this. I really appreciate it (and I really appreciate `mdbook-admonish`).

**Comment by tommilligan** [comment]
I ended up restructuring a bit to make the approach more extensible and testable - lots of refactoring that's only interesting to me, but the upshot is you can now add:

```toml
[preprocessor.admonish.renderer.test]
render_mode = "strip"
```

And it will enable the `admonish` syntax stripping as described above. Otherwise, it'll do nothing.

You can test this by simply enabling the same setting for the `html` renderer, if you like:

```toml
[preprocessor.admonish.renderer.html]
render_mode = "strip"
```

I have a few more bits of documentation to tidy up, but I'll put out a minor release with this in asap

**Pull request merged**
