### PR TITLE
Hide extra markers displayed in `Safari`.

### PR DESCRIPTION
**Pull request by CoralPink**
Hi!

As far as I know, this seems to be a `Safari` only phenomenon, but I have noticed that extra `▶︎` is being displayed where I have set `collapsible`.

~~~markdown
```admonish info title="example", collapsible=true
Example
```
~~~

before

...so why not add the following code to make this disappear?

```scss
:is(.admonition-title, summary.admonition-title) {

// …

  &::-webkit-details-marker {
    display: none;
  }

// …

}
```

after

I don't know if this is the right place...
is this the right place? 😅

### CODE REVIEW

**Comment by tommilligan** [comment]
Hi, thanks for the report and the contribution - sorry I didn't get round to doing anything about this for so long.

I updated your branch with what I think should be the right place to fix this - I'm not able to test this locally, would you mind testing and seeing if this still fixes it for you?

**Comment by CoralPink** [comment]
Hi, I've tried it locally and it seems to be working as expected!

Result:
display-none

Comment out:
comment-out

However, I'm a little worried because I can't find any documentation for `-webkit-details-marker` when I looked again...

…I hope it's just that I haven't found it... 🫠

**Comment by tommilligan** [comment]
I found a reference to it [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#default_style) where they suggest exactly what you did in this PR (using display none to hide it), so looks all good to me

**Review by tommilligan — APPROVED** [review]

**Comment by CoralPink** [comment]
I see!

Thanks for telling me!😆

**Pull request merged**
