### PR TITLE
fix: additional-css UNIX style path normalization

### LINKED ISSUE #161: additional-css UNIX style paths
UNIX style paths should always be used for `additional-css`.
When running `mdbook-admonish` on a `UNIX` system, the paths are (correctly) normalized:
*Before*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
*After*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
On a Windows system, `mdbook-admonish` causes the paths to be (inaccurately) normalized and duplicated:
*Before*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
*After*:
```toml
additional-css = ['./path/to/mdbook-admonish.css', '.\path\to\mdbook-admonish.css']
```

### PR DESCRIPTION
**Pull request by carlocorradini**
Fix #161 

I'm not sure if certain tests (Windows only) are necessary 🤔

### CODE REVIEW

**Comment by tommilligan** [comment]
This looks great, thanks for sending a fix as well. I think we should add a unit test and the Windows platform to CI, which I'll look at doing now. I can see I tried before and then disabled it for some reason, let's find out why!

**Comment by tommilligan** [comment]
_sigh_ - sorry, I forgot that github behaves weirdly if I try to push to a contributor's PR branch, when it is also the default branch in your fork. (looks to revert your branch, and close this PR automatically)

I've opened a clone of your fix here, with some additional changes on top to add a Windows test for it. Looks good!

If you would like to push the changes back into this PR so you get github kudos for it, please do, otherwise I'll merge that clone PR in a few days.

**Comment by tommilligan** [comment]
I have also added a note in the contributing guide #164 to remind myself of this behaviour in future

**Comment by carlocorradini** [comment]
All good for me 🤗
Merge! 🥳

**Pull request closed without merging**
